<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open MenuAll ItemsAboutLogoutReset App _b0c94b</name>
   <tag></tag>
   <elementGuidId>6856e1df-d4b9-433b-82d5-994cb2891d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#page_wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#page_wrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b70c3656-8b52-4093-b949-a8c13bf62411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page_wrapper</value>
      <webElementGuid>14713fbf-d8ad-465b-83e5-7eda155458ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page_wrapper</value>
      <webElementGuid>e255a52b-6524-46b7-ad55-e0f78090339c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open MenuAll ItemsAboutLogoutReset App StateClose MenuSwag LabsYour CartQTYDescriptionContinue ShoppingCheckoutTwitterFacebookLinkedIn© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy</value>
      <webElementGuid>2af7a1c7-8100-4178-bac1-943ebf8bb9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)</value>
      <webElementGuid>d2fdc384-6863-4df6-8611-c15fb16bf7ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']</value>
      <webElementGuid>58964bad-45fd-4866-9913-f30395543647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>c781fbb8-5a3e-4fc7-a5fb-731af339445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>7ba48090-df91-4d3c-a2df-e4b721f422b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'page_wrapper' and (text() = 'Open MenuAll ItemsAboutLogoutReset App StateClose MenuSwag LabsYour CartQTYDescriptionContinue ShoppingCheckoutTwitterFacebookLinkedIn© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy' or . = 'Open MenuAll ItemsAboutLogoutReset App StateClose MenuSwag LabsYour CartQTYDescriptionContinue ShoppingCheckoutTwitterFacebookLinkedIn© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy')]</value>
      <webElementGuid>1554592f-005e-4cee-ad1c-516499449894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
